language: pt
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "word"
    min_ngram: 1
    max_ngram: 2
  - name: DIETClassifier
    epochs: 100
    hidden_layers_sizes:
      text: [256, 128]
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy